### ISSUE TITLE
Broken listener

### ISSUE THREAD

**Issue by vitome** [peppelinux/pyDHCPStarvator#2]
Hi, I'm suspecting that when moving to python3 something broke: I'm trying to play with the listener starvation attack (as in README), but whenever the listener receives a packet, it responds with 
``  File "/root/pyDHCPStarvator/arp_ping.py", line 17, in get_mac
arp_hdr = ARP(op=ARP.who_has, pdst=ip_addr) # ARP header with 'who has this IP with MAC?'
File "/usr/local/lib/python3.7/dist-packages/scapy/base_classes.py", line 246, in __getattr__  raise AttributeError(attr)
AttributeError: who_has``
I also tried to "hard code" the op=1, but then another error happens: 
``  File "/usr/local/lib/python3.7/dist-packages/scapy/route.py", line 155, in route
    atol_dst = atol(_dst)
  File "/usr/local/lib/python3.7/dist-packages/scapy/utils.py", line 468, in atol
    ip = inet_aton(socket.gethostbyname(x))
socket.gaierror: [Errno -2] Name or service not known
``
Should I switch to python2 branch (18 commits behind)?

**Comment by peppelinux** [comment]
Hi @vitome,
Probably it's a version problem, try to pull my last commit and ensure to use a good virtualenv with package included in requirements.txt

I admit that I should spend some hours to do some cleanup and publish an official release, installable via pypi.
Let me know and thank you for the report

**Comment by peppelinux** [comment]
See also this:
https://github.com/peppelinux/pyDHCPStarvator/pull/1/files

I merged and tested without any problem at that time but if you can0t rid of this please try to use that old implementation of mine instead of the commits made by @rishithaminol 

This project should also came with unit tests, if time will permit ...
I accept contributions!

**Comment by vitome** [comment]
Hi Peppelinux, thanks for your answer. I tried in a couple of fresh new installations and I always get the same error:
```
~/tmp/pyDHCPStarvator$ sudo python3 listener.py -i enp0s3 -starvation-attack
Start DHCP listener on interface 'enp0s3' with filter 'port 68 and port 67'
Traceback (most recent call last):
  File "listener.py", line 108, in <module>
    args.pfilter)
  File "listener.py", line 62, in listen
    sniff(iface=iface, filter=pfilter, prn=pkt_callback, store=0)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sendrecv.py", line 925, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.6/dist-packages/scapy/sessions.py", line 47, in on_packet_received
    result = self.prn(pkt)
  File "listener.py", line 46, in pkt_callback
    print("DHCP OFFER from: {} [{}]".format(router_ip, get_mac(router_ip, conf.iface)))
  File "/home/user/tmp/pyDHCPStarvator/arp_ping.py", line 17, in get_mac
    arp_hdr = ARP(op=ARP.who_has, pdst=ip_addr) # ARP header with 'who has this IP with MAC?'
  File "/usr/local/lib/python3.6/dist-packages/scapy/base_classes.py", line 246, in __getattr__
    raise AttributeError(attr)
AttributeError: who_has
```
It seems the change you merged...

**Comment by peppelinux** [comment]
Please revert that change and do a test, if everything will works fine I'll fix in a new commit

**Comment by peppelinux** [comment]
Done here:
https://github.com/peppelinux/pyDHCPStarvator/commit/46e8bb026bdec3b9f220784ef9afff3c5103c8bd

please do a test

**Comment by vitome** [comment]
Thanks, in the new commit, the error disappeared. I'll do some other test with this commit.

**Comment by peppelinux** [comment]
@vitome I'm looking for contributors on this project, if you have attitude feel free to join
The roadmap will simply have a general code refactor for pypi packaging.
There would be also need to do some unit tests, to enable TOX and CI in github. This would be awesome.

Thank you

**Comment by peppelinux** [comment]
Ah, at last but not at least, I would like to ask to put a star on this project, I'll be grateful

**Comment by peppelinux** [comment]
Fixed, going to close
